[build]
target = "thumbv7em-none-eabihf"

# For micro:bit v2
[target.thumbv7em-none-eabihf]
runner = "probe-rs run --protocol=swd"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
]
